#!/bin/bash
echo "Installed: "
arm-none-eabi-gcc     --version | head -n 1
arm-none-eabi-g++     --version | head -n 1
arm-none-eabi-size    --version | head -n 1
arm-none-eabi-objcopy --version | head -n 1
arm-none-eabi-readelf --version | head -n 1

echo "Reviewing arm-none-eabi-gdb dependencies..."

if  ldd "$(which arm-none-eabi-gdb)" | grep '=> not found' ; then
    echo "--------------------------------------------"
    echo "arm-none-eabi-gdb dependencies are not met."
    echo "You may wish to use this embarrassing kludge as a work-around to fix the issue:"
    echo "   curl http://security.debian.org/debian-security/pool/updates/main/n/ncurses/libncurses5_6.1+20181013-2+deb10u5_amd64.deb -L -o libncurses.deb"
    echo "   curl http://security.debian.org/debian-security/pool/updates/main/n/ncurses/libtinfo5_6.1+20181013-2+deb10u5_amd64.deb   -L -o libtinfo.deb"
    echo "   sudo dpkg -i libncurses.deb libtinfo.deb"
    echo "   sudo ln -s /lib/x86_64-linux-gnu/libncursesw.so.6 /lib/x86_64-linux-gnu/libncursesw.so.5"
    echo "--------------------------------------------"
else
    arm-none-eabi-gdb     --version | head -n 1
fi

