name: DebianBuild

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Run builder
      run: ./create_deb.sh
    - name: Archive .deb files
      uses: actions/upload-artifact@v4
      with:
        name: deb-files
        path: ./*.deb
